export const recentStudents = [
  {
    img: "recentStudent_img1",
    name: "Melinda Moses",
    data: "01 Jan 2023",
    coursesCount: "2",
  },
  {
    img: "recentStudent_img2",
    name: "John Smith",
    data: "12 Feb 2023",
    coursesCount: "3",
  },
  {
    img: "recentStudent_img3",
    name: "David Son",
    data: "18 Mar 2023",
    coursesCount: "2",
  },
  {
    img: "recentStudent_img4",
    name: "Jones paul",
    data: "25 Apl 2023",
    coursesCount: "1",
  },
  {
    img: "recentStudent_img1",
    name: "Melinda Moses",
    data: "01 Jan 2024",
    coursesCount: "3",
  },
  {
    img: "recentStudent_img2",
    name: "Sharon",
    data: "14 Jan 2024",
    coursesCount: "2",
  },
  {
    img: "recentStudent_img3",
    name: "Ancy",
    data: "01 Feb 2024",
    coursesCount: "4",
  },
];

export const courses = [
  {
    "#40": 1,
    courseName_No: "AI0031",
    Name: "Artificial intelligence",
    shortCourse_No: "AI",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Artificial intelligence is the simulation of human intelligence Artificial intelligence is the simulation of human intelligence",
  },
  {
    "#40": 2,
    courseName_No: "PR0031",
    Name: "Public Relations",
    shortCourse_No: "Marketing",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 3,
    courseName_No: "GD0031",
    Name: "Graphic Design",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 4,
    courseName_No: "UD0031",
    Name: "UI/UX Design",
    shortCourse_No: "design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 5,
    courseName_No: "WD0031",
    Name: "Web Design",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 6,
    courseName_No: "MG0031",
    Name: "Motion Graphics",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 7,
    courseName_No: "AI0031",
    Name: "Animation",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 8,
    courseName_No: "PD0031",
    Name: "Product Design",
    shortCourse_No: "Desing",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 9,
    courseName_No: "BE0031",
    Name: "Back End",
    shortCourse_No: "Development",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 10,
    courseName_No: "PR0031",
    Name: "Public Relations",
    shortCourse_No: "Marketing",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 11,
    courseName_No: "GD0031",
    Name: "Graphic Design",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 12,
    courseName_No: "UD0031",
    Name: "UI/UX Design",
    shortCourse_No: "design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 13,
    courseName_No: "WD0031",
    Name: "Web Design",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 14,
    courseName_No: "MG0031",
    Name: "Motion Graphics",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
  {
    "#40": 15,
    courseName_No: "AI0031",
    Name: "Animation",
    shortCourse_No: "Design",
    StudentsEnrolled: "10",
    FacultyAllotted: "20",
    TotalSeats: "25",
    Duration: "41",
    RegFee: "₹ 50.00",
    TutionFee: "₹ 550.00",
    MaterialFee: "₹ 550.00",
    TotalFee: "₹ 800.00",
    GrandTotal: "₹ 20,000.000",
    info_No:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit asdm Lorem ipsum dolor sit amet",
  },
];

export const markSheetEntry = [
  {
    img: "marksheet entry img 1.png",
    "Course Name": "Artificial Intelligence",
    code: "AI0031",
    category: "AI",
    "Pro.Name": "Michael Bracewell",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 2.png",
    "Course Name": "Public Relations",
    code: "PR0031",
    category: "Marketing",
    "Pro.Name": "John Smith",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 3.png",
    "Course Name": "Data Scirnce and Analytics",
    code: "DS0053",
    category: "Data Science",
    "Pro.Name": "Alan",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 4.png",
    "Course Name": "Graphic Design",
    code: "GDI0031",
    category: "Dedign",
    "Pro.Name": "David Jhon",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 5.png",
    "Course Name": "BlockChain and Cryptocurrency",
    code: "AI0031",
    category: "Investing & Trading",
    "Pro.Name": "Stephen",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 6.png",
    "Course Name": "UI/Ux Design",
    code: "UX0031",
    category: "Design",
    "Pro.Name": "Martin Guptill",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 7.png",
    "Course Name": "Web Design",
    code: "WB0031",
    category: "Design",
    "Pro.Name": "Markaram",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 8.png",
    "Course Name": "Motion Graphics",
    code: "MG0031",
    category: "Design",
    "Pro.Name": "Jimmy Neesham",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
  {
    img: "marksheet entry img 9.png",
    "Course Name": "Product Design",
    code: "UX0031",
    category: "Design",
    "Pro.Name": "Daryl Mitchell",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },

  {
    img: "marksheet entry img 10.png",
    "Course Name": "Interior Design",
    code: "WB0031",
    category: "Design",
    "Pro.Name": "Daryl Mitchell",
    "Total Student": "10",
    "Total Assesment": "3",
    "Overall Percentage": "50",
  },
];

export const studentAssesementMarkList = [
  {
    courseName: "Artificial Intelligence",
    courseId: "AI0031",
    courseLogo: "marksheet entry img 1.png",
    shortFor: "AI",
    Prof: "Michael Bracewell",
    CourseDetails: [
      {
        img: "Marksheet entry_AI_img 1.png",
        Name: "Liam Livingstone",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "41",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 2.png",
        Name: "Finn Allen",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 3.png",
        Name: "Lachlan Ferguson",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 4.png",
        Name: "Martin Guptill",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 5.png",
        Name: "Peson 1",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 6.png",
        Name: "Chris Woakes",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 7.png",
        Name: "David Willey",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 8.png",
        Name: "Charline",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 9.png",
        Name: "Chris Woakes",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
      {
        img: "Marksheet entry_AI_img 1.png",
        Name: "David Willey",
        "Assesement 1": "10",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "D",
      },
    ],
  },
  {
    courseName: "Public Relations",
    courseId: "PR0031",
    courseLogo: "marksheet entry img 2.png",
    shortFor: "PR",
    Prof: "Sharon",
    CourseDetails: [
      {
        img: "Marksheet entry_AI_img 2.png",
        Name: "Liam Livingstone",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "41",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 5.png",
        Name: "Finn Allen",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 1.png",
        Name: "Lachlan Ferguson",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 7.png",
        Name: "Martin Guptill",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 5.png",
        Name: "Peson 1",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 8.png",
        Name: "Chris Woakes",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 9.png",
        Name: "David Willey",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 7.png",
        Name: "Charline",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 9.png",
        Name: "Chris Woakes",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
      {
        img: "Marksheet entry_AI_img 1.png",
        Name: "David Willey",
        "Assesement 1": "30",
        "Assesement 2": "20",
        "Assesement 3": "25",
        Percentage: "37",
        Grade: "C",
      },
    ],
  },
];

export const eventList = [
  {
    event: "Programming",
    dateAndTime: "13 Dec 2023 | 5 PM - 9.30 PM",
    time: "5 PM - 9.30 PM",
  },
  {
    event: "Culturals",
    dateAndTime: "13 Dec 2023 | 5 PM - 9.30 PM",
    time: "5 PM - 9.30 PM",
  },
  {
    event: "Birthday",
    dateAndTime: "15 Dec 2023 | 5 PM - 9.30 PM",
    time: "5 PM - 9.30 PM",
  },
  {
    event: "Anniversary",
    dateAndTime: "13 Dec 2023 | 5 PM - 9.30 PM",
    time: "5 PM - 9.30 PM",
  },
];

export const upCommingEvent = [
  {
    event: "Easter",
    date: "30 Mar 2024",
  },
  {
    event: "Christmas",
    date: "25 Dec 2024",
  },
  {
    event: "NewYear",
    date: "01 Jan 2025",
  },
];

export const studentsDetails = [
  {
    img: "faculty img 1.png",
    Name: "Malynne",
    ID: "PRE2218",
    "Course Name": "Artificial Intelligence",
    Gender: "Female",
    DOB: "2 Feb 1995",
    "Mob.No": "7896541236",
    "Email ID": "malynne@gmail.com",
  },
  {
    img: "faculty img 2.png",
    Name: "Levell Scott",
    ID: "PRE2212",
    "Course Name": "Public Relations",
    Gender: "Male",
    DOB: "3 Feb 1996",
    "Mob.No": "7896541236",
    "Email ID": "Levell@gmail.com",
  },
  {
    img: "faculty img 3.png",
    Name: "Levell Shat",
    ID: "PRE2213",
    "Course Name": "Graphic Design",
    Gender: "Male",
    DOB: "15 Jan 1996",
    "Mob.No": "8523697412",
    "Email ID": "shat@gmail.com",
  },
  {
    img: "faculty img 4.png",
    Name: "Minnie",
    ID: "PRE2214",
    "Course Name": "UI/UX Design",
    Gender: "Female",
    DOB: "7 Mar 1994",
    "Mob.No": "8547961236",
    "Email ID": "minnie@gmail.com",
  },
  {
    img: "faculty img 5.png",
    Name: "Lois A",
    ID: "PRE2215",
    "Course Name": "Wed Design",
    Gender: "Female",
    DOB: "2 Feb 1995",
    "Mob.No": "7412589632",
    "Email ID": "lois@gmail.com",
  },
  {
    img: "faculty img 6.png",
    Name: "Calvin",
    ID: "PRE2217",
    "Course Name": "Motion Graphics",
    Gender: "Female",
    DOB: "2 Feb 1995",
    "Mob.No": "9632587412",
    "Email ID": "calvin@gmail.com",
  },
  {
    img: "faculty img 7.png",
    Name: "Jeo kelly",
    ID: "PRE2234",
    "Course Name": "Animation",
    Gender: "Male",
    DOB: "2 Feb 1995",
    "Mob.No": "7896541236",
    "Email ID": "Jeo@gmail.com",
  },
  {
    img: "faculty img 8.png",
    Name: "Vincent",
    ID: "PRE2218",
    "Course Name": "Product Design",
    Gender: "Male",
    DOB: "2 Des 1995",
    "Mob.No": "8523697412",
    "Email ID": "vincent@gmail.com",
  },
  {
    img: "faculty img 9.png",
    Name: "John Kennedy",
    ID: "PRE2230",
    "Course Name": "Product Design",
    Gender: "Female",
    DOB: "2 Feb 1995",
    "Mob.No": "7896541236",
    "Email ID": "jhon@gmail.com",
  },
  {
    img: "faculty img 1.png",
    Name: "Stephen Matthew",
    ID: "PRE2218",
    "Course Name": "UI/UX Design",
    Gender: "Male",
    DOB: "2 Feb 1995",
    "Mob.No": "7896541236",
    "Email ID": "matthew@gmail.com",
  },
  {
    img: "faculty img 2.png",
    Name: "John",
    ID: "PRE2219",
    "Course Name": "Artificial Intelligence",
    Gender: "Male",
    DOB: "15 May 1988",
    "Mob.No": "9876543210",
    "Email ID": "john@example.com",
  },
  {
    img: "faculty img 3.png",
    Name: "Emily",
    ID: "PRE2220",
    "Course Name": "Artificial Intelligence",
    Gender: "Female",
    DOB: "10 Oct 1990",
    "Mob.No": "8765432109",
    "Email ID": "emily@example.com",
  },
  {
    img: "faculty img 4.png",
    Name: "Daniel",
    ID: "PRE2221",
    "Course Name": "Artificial Intelligence",
    Gender: "Male",
    DOB: "25 Mar 1985",
    "Mob.No": "7654321098",
    "Email ID": "daniel@example.com",
  },
  {
    img: "faculty img 5.png",
    Name: "Sophia",
    ID: "PRE2222",
    "Course Name": "Artificial Intelligence",
    Gender: "Female",
    DOB: "5 Jul 1993",
    "Mob.No": "6543210987",
    "Email ID": "sophia@example.com",
  },
  {
    img: "faculty img 6.png",
    Name: "Michael",
    ID: "PRE2223",
    "Course Name": "Artificial Intelligence",
    Gender: "Male",
    DOB: "20 Nov 1983",
    "Mob.No": "5432109876",
    "Email ID": "michael@example.com",
  },
  {
    img: "faculty img 7.png",
    Name: "Emma",
    ID: "PRE2224",
    "Course Name": "Artificial Intelligence",
    Gender: "Female",
    DOB: "12 Dec 1991",
    "Mob.No": "4321098765",
    "Email ID": "emma@example.com",
  },
  {
    img: "faculty img 8.png",
    Name: "William",
    ID: "PRE2225",
    "Course Name": "Artificial Intelligence",
    Gender: "Male",
    DOB: "8 Aug 1980",
    "Mob.No": "3210987654",
    "Email ID": "william@example.com",
  },
  {
    img: "faculty img 9.png",
    Name: "Olivia",
    ID: "PRE2226",
    "Course Name": "Artificial Intelligence",
    Gender: "Female",
    DOB: "18 Sep 1992",
    "Mob.No": "2109876543",
    "Email ID": "olivia@example.com",
  },
  {
    img: "faculty img 2.png",
    Name: "James",
    ID: "PRE2227",
    "Course Name": "Artificial Intelligence",
    Gender: "Male",
    DOB: "30 Apr 1987",
    "Mob.No": "1098765432",
    "Email ID": "james@example.com",
  },
  {
    img: "faculty img 2.png",
    Name: "Jonathan",
    ID: "PRE2219",
    "Course Name": "Public Relations",
    Gender: "Male",
    DOB: "15 May 1987",
    "Mob.No": "9876543210",
    "Email ID": "jonathan@example.com",
  },
  {
    img: "faculty img 3.png",
    Name: "Sophia",
    ID: "PRE2220",
    "Course Name": "Public Relations",
    Gender: "Female",
    DOB: "10 Oct 1990",
    "Mob.No": "8765432109",
    "Email ID": "sophia@example.com",
  },
  {
    img: "faculty img 4.png",
    Name: "Elijah",
    ID: "PRE2221",
    "Course Name": "Public Relations",
    Gender: "Male",
    DOB: "3 Mar 1980",
    "Mob.No": "7654321098",
    "Email ID": "elijah@example.com",
  },
  {
    img: "faculty img 5.png",
    Name: "Olivia",
    ID: "PRE2222",
    "Course Name": "Public Relations",
    Gender: "Female",
    DOB: "25 Jul 1985",
    "Mob.No": "6543210987",
    "Email ID": "olivia@example.com",
  },
  {
    img: "faculty img 6.png",
    Name: "Benjamin",
    ID: "PRE2223",
    "Course Name": "Public Relations",
    Gender: "Male",
    DOB: "19 Sep 1993",
    "Mob.No": "5432109876",
    "Email ID": "benjamin@example.com",
  },
  {
    img: "faculty img 7.png",
    Name: "Charlotte",
    ID: "PRE2224",
    "Course Name": "Public Relations",
    Gender: "Female",
    DOB: "8 Apr 1976",
    "Mob.No": "4321098765",
    "Email ID": "charlotte@example.com",
  },
  {
    img: "faculty img 8.png",
    Name: "Henry",
    ID: "PRE2225",
    "Course Name": "Public Relations",
    Gender: "Male",
    DOB: "12 Nov 1983",
    "Mob.No": "3210987654",
    "Email ID": "henry@example.com",
  },
  {
    img: "faculty img 9.png",
    Name: "Amelia",
    ID: "PRE2226",
    "Course Name": "Public Relations",
    Gender: "Female",
    DOB: "30 Dec 1979",
    "Mob.No": "2109876543",
    "Email ID": "amelia@example.com",
  },
  {
    img: "faculty img 3.png",
    Name: "Lucas",
    ID: "PRE2227",
    "Course Name": "Public Relations",
    Gender: "Male",
    DOB: "17 Jun 1991",
    "Mob.No": "1098765432",
    "Email ID": "lucas@example.com",
  },
  {
    img: "faculty img 5.png",
    Name: "Mia",
    ID: "PRE2228",
    "Course Name": "Public Relations",
    Gender: "Female",
    DOB: "9 Aug 1988",
    "Mob.No": "0987654321",
    "Email ID": "mia@example.com",
  },
];

export const coursesInfo = [
  {
    courseName: "Artificial Intelligence",
    code: "AI0031",
    short: "AI",
    img: "studets card view_AI.png",
  },
  {
    courseName: "Public Relations",
    code: "PR0031",
    short: "Marketing",
    img: "studets card view_PR.png",
  },
  {
    courseName: "Graphic Design",
    code: "GD0031",
    short: "Design",
    img: "studets card view_GD.png",
  },
  {
    courseName: "BlockChain and Cryoticurrency",
    code: "BG2452",
    short: "AI",
    img: "studets card view_GD 2.png",
  },
  {
    courseName: "UI/UX Design",
    code: "UD0031",
    short: "Design",
    img: "studets card view_BC.png",
  },
  {
    courseName: "Web Design",
    code: "WD0031",
    short: "Design",
    img: "UX.png",
  },
  {
    courseName: "Motion Graphics",
    code: "MG0031",
    short: "Design",
    img: "studets card view_Web design.png",
  },
  {
    courseName: "Animation",
    code: "AN0031",
    short: "Design",
    img: "studets card view_MG.png",
  },
];

export const faculties = [
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "John Smith",
        Id: "AI2218",
        From: "12 Dec 2023",
        To: "12 Mar 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "2 Feb 1985",
        "Mob.No": "7896541236",
      },
    ],
  },

  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Michael Brown",
        Id: "AI2220",
        From: "10 Feb 2024",
        To: "10 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Mar 1980",
        "Mob.No": "7896541238",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Sophia Martinez",
        Id: "AI2221",
        From: "20 Mar 2024",
        To: "20 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Nov 1987",
        "Mob.No": "7896541239",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "David Wilson",
        Id: "AI2222",
        From: "25 Apr 2024",
        To: "25 Jul 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Aug 1983",
        "Mob.No": "7896541240",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Olivia Taylor",
        Id: "AI2223",
        From: "1 May 2024",
        To: "1 Aug 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Oct 1986",
        "Mob.No": "7896541241",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 7.png",
        Name: "James Anderson",
        Id: "AI2224",
        From: "10 Jun 2024",
        To: "10 Sep 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "30 Dec 1978",
        "Mob.No": "7896541242",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Isabella Garcia",
        Id: "AI2225",
        From: "15 Jul 2024",
        To: "15 Oct 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "12 Jan 1981",
        "Mob.No": "7896541243",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 9.png",
        Name: "Liam Brown",
        Id: "AI2226",
        From: "20 Aug 2024",
        To: "20 Nov 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "8 Feb 1975",
        "Mob.No": "7896541244",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Ava Moore",
        Id: "AI2227",
        From: "25 Sep 2024",
        To: "25 Dec 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "18 Mar 1984",
        "Mob.No": "7896541245",
      },
    ],
  },
  {
    name: "Artificial Intelligence",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "Noah Clark",
        Id: "AI2228",
        From: "1 Oct 2024",
        To: "1 Jan 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "22 Apr 1973",
        "Mob.No": "7896541246",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 9.png",
        Name: "Emily Johnson",
        Id: "PRF1234",
        From: "15 Jan 2024",
        To: "15 Apr 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Sep 1985",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Michael Davis",
        Id: "PRF5678",
        From: "10 Feb 2024",
        To: "10 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Mar 1979",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 7.png",
        Name: "Sarah Parker",
        Id: "PRF9012",
        From: "20 Mar 2024",
        To: "20 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Nov 1990",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "David Thompson",
        Id: "PRF3456",
        From: "1 Apr 2024",
        To: "1 Jul 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "12 Aug 1982",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Jessica Moore",
        Id: "PRF7890",
        From: "5 May 2024",
        To: "5 Aug 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Jan 1987",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Daniel Wilson",
        Id: "PRF2345",
        From: "10 Jun 2024",
        To: "10 Sep 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Mar 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Amanda Taylor",
        Id: "PRF6789",
        From: "15 Jul 2024",
        To: "15 Oct 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "30 Oct 1984",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "Matthew Garcia",
        Id: "PRF1234",
        From: "20 Aug 2024",
        To: "20 Nov 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "8 Jul 1975",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Sophia Martinez",
        Id: "PRF5678",
        From: "25 Sep 2024",
        To: "25 Dec 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "18 Apr 1992",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Public Relations",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "James Thompson",
        Id: "PRF9012",
        From: "1 Oct 2024",
        To: "1 Jan 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "22 Nov 1986",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 9.png",
        Name: "Alice Johnson",
        Id: "QA123",
        From: "10 Jan 2024",
        To: "10 Apr 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "15 Jul 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "John Doe",
        Id: "QA456",
        From: "15 Feb 2024",
        To: "15 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "20 Sep 1975",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 7.png",
        Name: "Ella Smith",
        Id: "QA789",
        From: "20 Mar 2024",
        To: "20 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "25 Dec 1988",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "David Wilson",
        Id: "QA101",
        From: "25 Apr 2024",
        To: "25 Jul 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "30 Jan 1983",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Sophia Lee",
        Id: "QA102",
        From: "1 May 2024",
        To: "1 Aug 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Mar 1992",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Daniel Brown",
        Id: "QA103",
        From: "10 Jun 2024",
        To: "10 Sep 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "12 Aug 1977",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Olivia Taylor",
        Id: "QA104",
        From: "15 Jul 2024",
        To: "15 Oct 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Nov 1986",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "William Clark",
        Id: "QA105",
        From: "20 Aug 2024",
        To: "20 Nov 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Apr 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Ava Martinez",
        Id: "QA106",
        From: "25 Sep 2024",
        To: "25 Dec 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "30 Oct 1989",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "James Rodriguez",
        Id: "QA107",
        From: "1 Oct 2024",
        To: "1 Jan 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "5 Jun 1979",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        Name: "Mia Hernandez",
        Id: "QA108",
        From: "10 Nov 2024",
        To: "10 Feb 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "15 Dec 1984",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Benjamin Nguyen",
        Id: "QA109",
        From: "15 Dec 2024",
        To: "15 Mar 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "20 Mar 1983",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Charlotte Perez",
        Id: "QA110",
        From: "20 Jan 2025",
        To: "20 Apr 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "25 Feb 1990",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "Ethan Walker",
        Id: "QA111",
        From: "25 Feb 2025",
        To: "25 May 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "30 Apr 1987",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Quality Analyst",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Amelia Gonzalez",
        Id: "QA112",
        From: "1 Mar 2025",
        To: "1 Jun 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Jul 1981",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "Alice Johnson",
        Id: "WD1234",
        From: "15 Jan 2024",
        To: "15 Apr 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Sep 1985",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Bob Smith",
        Id: "WD5678",
        From: "10 Feb 2024",
        To: "10 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Mar 1979",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "Eva Brown",
        Id: "WD9012",
        From: "20 Mar 2024",
        To: "20 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Nov 1990",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "John Doe",
        Id: "WD3456",
        From: "1 Jan 2024",
        To: "1 Apr 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Feb 1982",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Laura Garcia",
        Id: "WD7890",
        From: "5 Feb 2024",
        To: "5 May 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Jun 1976",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Michael Lee",
        Id: "WD2345",
        From: "8 Mar 2024",
        To: "8 Jun 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "12 Aug 1989",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Sophia Martinez",
        Id: "WD6789",
        From: "12 Apr 2024",
        To: "12 Jul 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "25 Oct 1995",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "William Johnson",
        Id: "WD5432",
        From: "18 May 2024",
        To: "18 Aug 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "8 Dec 1983",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Emma Garcia",
        Id: "WD8901",
        From: "21 Jun 2024",
        To: "21 Sep 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "15 Apr 1987",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 9",
        Name: "David Rodriguez",
        Id: "WD6789",
        From: "30 Jul 2024",
        To: "30 Oct 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "4 Mar 1974",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Olivia Martinez",
        Id: "WD3452",
        From: "5 Sep 2024",
        To: "5 Dec 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Aug 1992",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "James Johnson",
        Id: "WD6789",
        From: "10 Oct 2024",
        To: "10 Jan 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "12 May 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Sophia Brown",
        Id: "WD8901",
        From: "15 Nov 2024",
        To: "15 Feb 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "18 Jul 1986",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Developer",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Daniel Smith",
        Id: "WD3452",
        From: "20 Dec 2024",
        To: "20 Mar 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "22 Sep 1997",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Alice Johnson",
        Id: "ANM1234",
        From: "10 Jan 2024",
        To: "10 Apr 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "15 Aug 1986",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 9",
        Name: "David Miller",
        Id: "ANM5678",
        From: "5 Feb 2024",
        To: "5 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "20 Nov 1979",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "Sophia Brown",
        Id: "ANM9012",
        From: "15 Mar 2024",
        To: "15 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Apr 1992",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Michael Clark",
        Id: "ANM3456",
        From: "20 Apr 2024",
        To: "20 Jul 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Sep 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Emma Wilson",
        Id: "ANM7890",
        From: "25 May 2024",
        To: "25 Aug 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Jun 1995",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Matthew Taylor",
        Id: "ANM2345",
        From: "30 Jun 2024",
        To: "30 Sep 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Mar 1988",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Olivia Garcia",
        Id: "ANM6789",
        From: "5 Aug 2024",
        To: "5 Nov 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Jul 1991",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "William Martinez",
        Id: "ANM0123",
        From: "10 Sep 2024",
        To: "10 Dec 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "10 Jan 1985",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Sophie Hernandez",
        Id: "ANM4567",
        From: "15 Oct 2024",
        To: "15 Jan 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "25 Dec 1983",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Daniel Anderson",
        Id: "ANM8901",
        From: "20 Nov 2024",
        To: "20 Feb 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "30 Apr 1982",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Amelia Wright",
        Id: "ANM3456",
        From: "25 Dec 2024",
        To: "25 Mar 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Oct 1978",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Ethan White",
        Id: "ANM7890",
        From: "1 Jan 2025",
        To: "1 Apr 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "20 Feb 1976",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Mia Thompson",
        Id: "ANM2345",
        From: "5 Feb 2025",
        To: "5 May 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "15 Jul 1984",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Animation",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "James Lee",
        Id: "ANM6789",
        From: "10 Mar 2025",
        To: "10 Jun 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "5 Sep 1974",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Alice Johnson",
        Id: "MGF1234",
        From: "15 Jan 2024",
        To: "15 Apr 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Sep 1985",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Bob Smith",
        Id: "MGF5678",
        From: "10 Feb 2024",
        To: "10 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Mar 1979",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "Carol Williams",
        Id: "MGF9012",
        From: "20 Mar 2024",
        To: "20 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Nov 1990",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "David Brown",
        Id: "MGF3456",
        From: "10 Apr 2024",
        To: "10 Jul 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Aug 1982",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Emily Taylor",
        Id: "MGF7890",
        From: "25 May 2024",
        To: "25 Aug 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Apr 1987",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Frank Clark",
        Id: "MGF2345",
        From: "15 Jun 2024",
        To: "15 Sep 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "10 Jan 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Grace Martinez",
        Id: "MGF6789",
        From: "10 Jul 2024",
        To: "10 Oct 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 May 1993",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "Henry Rodriguez",
        Id: "MGF5432",
        From: "20 Aug 2024",
        To: "20 Nov 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Jul 1984",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 9",
        Name: "Ivy Adams",
        Id: "MGF0987",
        From: "15 Sep 2024",
        To: "15 Dec 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Oct 1989",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Jack Evans",
        Id: "MGF6543",
        From: "10 Oct 2024",
        To: "10 Jan 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "5 Feb 1977",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Kelly Wilson",
        Id: "MGF2109",
        From: "20 Nov 2024",
        To: "20 Feb 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "15 Mar 1992",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Leo Harris",
        Id: "MGF7654",
        From: "15 Dec 2024",
        To: "15 Mar 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "10 Apr 1986",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Megan Thompson",
        Id: "MGF3210",
        From: "10 Jan 2025",
        To: "10 Apr 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 May 1995",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Motion Graphics",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "Nathan Lee",
        Id: "MGF8765",
        From: "20 Feb 2025",
        To: "20 May 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Jun 1988",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Alice Johnson",
        Id: "WD121",
        From: "15 Jan 2024",
        To: "15 Apr 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Sep 1985",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Bob Smith",
        Id: "WD456",
        From: "10 Feb 2024",
        To: "10 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Mar 1979",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Ella Brown",
        Id: "WD789",
        From: "20 Mar 2024",
        To: "20 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Nov 1990",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "David Miller",
        Id: "WD101",
        From: "15 Apr 2024",
        To: "15 Jul 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "12 Dec 1983",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Sophia Lee",
        Id: "WD112",
        From: "10 May 2024",
        To: "10 Aug 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "18 Jun 1989",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 9",
        Name: "Jackson Wilson",
        Id: "WD131",
        From: "20 Jun 2024",
        To: "20 Sep 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "22 Aug 1975",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Emma Taylor",
        Id: "WD145",
        From: "15 Jul 2024",
        To: "15 Oct 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "30 Jan 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "William Anderson",
        Id: "WD156",
        From: "10 Aug 2024",
        To: "10 Nov 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "8 Apr 1982",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Olivia Martinez",
        Id: "WD171",
        From: "20 Sep 2024",
        To: "20 Dec 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "14 May 1977",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "James Brown",
        Id: "WD182",
        From: "15 Oct 2024",
        To: "15 Jan 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "6 Jul 1970",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Ava Wilson",
        Id: "WD199",
        From: "10 Nov 2024",
        To: "10 Feb 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "23 Sep 1986",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "John Johnson",
        Id: "WD201",
        From: "20 Dec 2024",
        To: "20 Mar 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "17 Nov 1981",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Grace Davis",
        Id: "WD218",
        From: "15 Jan 2025",
        To: "15 Apr 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "3 Feb 1974",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Daniel Wilson",
        Id: "WD223",
        From: "10 Feb 2025",
        To: "10 May 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "28 Mar 1972",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "Web Design",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Chloe Moore",
        Id: "WD240",
        From: "20 Mar 2025",
        To: "20 Jun 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "11 Dec 1988",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 8.png",
        Name: "Emily White",
        Id: "UID1234",
        From: "15 Jan 2024",
        To: "15 Apr 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "10 Sep 1985",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 9",
        Name: "Michael Brown",
        Id: "UID5678",
        From: "10 Feb 2024",
        To: "10 May 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Mar 1979",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 6.png",
        Name: "Sarah Green",
        Id: "UID9012",
        From: "20 Mar 2024",
        To: "20 Jun 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "5 Nov 1990",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 7",
        Name: "David Lee",
        Id: "UID3456",
        From: "10 Apr 2024",
        To: "10 Jul 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "15 Aug 1988",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "Emma Clark",
        Id: "UID7890",
        From: "5 May 2024",
        To: "5 Aug 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "20 Oct 1995",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Daniel Taylor",
        Id: "UID2345",
        From: "10 Jun 2024",
        To: "10 Sep 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "8 Feb 1982",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 4.png",
        Name: "Olivia Anderson",
        Id: "UID6789",
        From: "15 Jul 2024",
        To: "15 Oct 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "12 Dec 1989",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "John Walker",
        Id: "UID1230",
        From: "20 Aug 2024",
        To: "20 Nov 2024",
        period: "3 Months",
        Gender: "Male",
        DOB: "18 May 1976",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "Sophia Harris",
        Id: "UID5670",
        From: "25 Sep 2024",
        To: "25 Dec 2024",
        period: "3 Months",
        Gender: "Female",
        DOB: "30 Apr 1983",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Matthew Turner",
        Id: "UID9015",
        From: "1 Oct 2024",
        To: "1 Jan 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "25 Jun 1980",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 3.png",
        Name: "Chloe Baker",
        Id: "UID3450",
        From: "5 Nov 2024",
        To: "5 Feb 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "22 Mar 1987",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 2.png",
        Name: "James Martinez",
        Id: "UID7895",
        From: "10 Dec 2024",
        To: "10 Mar 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "17 Jul 1974",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 1.png",
        Name: "Lily Perez",
        Id: "UID2340",
        From: "15 Jan 2025",
        To: "15 Apr 2025",
        period: "3 Months",
        Gender: "Female",
        DOB: "3 Aug 1991",
        "Mob.No": "9876543210",
      },
    ],
  },
  {
    name: "UI/UX Design",
    facultyDetails: [
      {
        img: "faculty img 5.png",
        Name: "William Scott",
        Id: "UID6785",
        From: "20 Feb 2025",
        To: "20 May 2025",
        period: "3 Months",
        Gender: "Male",
        DOB: "11 Nov 1978",
        "Mob.No": "9876543210",
      },
    ],
  },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 2.png",
  //       Name: "Alice Johnson",
  //       Id: "GD1",
  //       From: "10 Jan 2024",
  //       To: "10 Apr 2024",
  //       period: "3 Months",
  //       Gender: "Female",
  //       DOB: "15 Nov 1980",
  //       "Mob.No": "1234567890",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 1.png",
  //       Name: "David Miller",
  //       Id: "GD2",
  //       From: "15 Feb 2024",
  //       To: "15 May 2024",
  //       period: "3 Months",
  //       Gender: "Male",
  //       DOB: "20 Apr 1975",
  //       "Mob.No": "2345678901",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 4.png",
  //       Name: "Sophia Garcia",
  //       Id: "GD3",
  //       From: "20 Mar 2024",
  //       To: "20 Jun 2024",
  //       period: "3 Months",
  //       Gender: "Female",
  //       DOB: "25 Sep 1992",
  //       "Mob.No": "3456789012",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 3.png",
  //       Name: "Daniel Clark",
  //       Id: "GD4",
  //       From: "10 Apr 2024",
  //       To: "10 Jul 2024",
  //       period: "3 Months",
  //       Gender: "Male",
  //       DOB: "30 Jan 1988",
  //       "Mob.No": "4567890123",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 5.png",
  //       Name: "Emma Wilson",
  //       Id: "GD5",
  //       From: "15 May 2024",
  //       To: "15 Aug 2024",
  //       period: "3 Months",
  //       Gender: "Female",
  //       DOB: "5 Jun 1995",
  //       "Mob.No": "5678901234",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 7",
  //       Name: "James Taylor",
  //       Id: "GD6",
  //       From: "20 Jun 2024",
  //       To: "20 Sep 2024",
  //       period: "3 Months",
  //       Gender: "Male",
  //       DOB: "10 Jul 1982",
  //       "Mob.No": "6789012345",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 6.png",
  //       Name: "Olivia Martinez",
  //       Id: "GD7",
  //       From: "10 Jul 2024",
  //       To: "10 Oct 2024",
  //       period: "3 Months",
  //       Gender: "Female",
  //       DOB: "15 Aug 1987",
  //       "Mob.No": "7890123456",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 8.png",
  //       Name: "Noah Anderson",
  //       Id: "GD8",
  //       From: "15 Aug 2024",
  //       To: "15 Nov 2024",
  //       period: "3 Months",
  //       Gender: "Male",
  //       DOB: "20 Sep 1980",
  //       "Mob.No": "8901234567",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 9",
  //       Name: "Ava Thomas",
  //       Id: "GD9",
  //       From: "20 Sep 2024",
  //       To: "20 Dec 2024",
  //       period: "3 Months",
  //       Gender: "Female",
  //       DOB: "25 Oct 1990",
  //       "Mob.No": "9012345678",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 1.png",
  //       Name: "Ethan Hernandez",
  //       Id: "GD10",
  //       From: "10 Oct 2024",
  //       To: "10 Jan 2025",
  //       period: "3 Months",
  //       Gender: "Male",
  //       DOB: "30 Nov 1985",
  //       "Mob.No": "0123456789",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 2.png",
  //       Name: "Mia Walker",
  //       Id: "GD11",
  //       From: "15 Nov 2024",
  //       To: "15 Feb 2025",
  //       period: "3 Months",
  //       Gender: "Female",
  //       DOB: "5 Dec 1997",
  //       "Mob.No": "1234567890",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 3.png",
  //       Name: "Liam Garcia",
  //       Id: "GD12",
  //       From: "20 Dec 2024",
  //       To: "20 Mar 2025",
  //       period: "3 Months",
  //       Gender: "Male",
  //       DOB: "15 Jan 1983",
  //       "Mob.No": "2345678901",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 4.png",
  //       Name: "Charlotte Lee",
  //       Id: "GD13",
  //       From: "10 Jan 2025",
  //       To: "10 Apr 2025",
  //       period: "3 Months",
  //       Gender: "Female",
  //       DOB: "20 Feb 1991",
  //       "Mob.No": "3456789012",
  //     },
  //   ],
  // },
  // {
  //   name: "Graphic Design",
  //   facultyDetails: [
  //     {
  //       img: "faculty img 5.png",
  //       Name: "Logan Perez",
  //       Id: "GD14",
  //       From: "15 Feb 2025",
  //       To: "15 May 2025",
  //       period: "3 Months",
  //       Gender: "Male",
  //       DOB: "25 Mar 1986",
  //       "Mob.No": "4567890123",
  //     },
  //   ],
  // },

]

export const studentEnrollmentChart = [
  {
    year: 2024,
    details: [
      {
        month: "Jan'23",
        numOfStudent: "600",
      },
      {
        month: "Feb'23",
        numOfStudent: "200",
      },
      {
        month: "Mar'23",
        numOfStudent: "400",
      },
      {
        month: "Apr'23",
      },
      {
        month: "May'23",
      },
      {
        month: "June'23",
      },
      {
        month: "July'23",
      },
      {
        month: "Aug'23",
      },
      {
        month: "Sep'23",
      },
      {
        month: "Oct'23",
      },
      {
        month: "Nov'23",
      },
      {
        month: "Des'23",
      },
    ],
  },
  {
    year: 2023,
    details: [
      {
        month: "Jan'23",
        numOfStudent: "600",
      },
      {
        month: "Feb'23",
        numOfStudent: "200",
      },
      {
        month: "Mar'23",
        numOfStudent: "400",
      },
      {
        month: "Apr'23",
        numOfStudent: "500",
      },
      {
        month: "May'23",
        numOfStudent: "300",
      },
      {
        month: "June'23",
        numOfStudent: "200",
      },
      {
        month: "July'23",
        numOfStudent: "400",
      },
      {
        month: "Aug'23",
        numOfStudent: "800",
      },
      {
        month: "Sep'23",
        numOfStudent: "400",
      },
      {
        month: "Oct'23",
        numOfStudent: "300",
      },
      {
        month: "Nov'23",
        numOfStudent: "700",
      },
      {
        month: "Des'23",
        numOfStudent: "800",
      },
    ],
  },
  {
    year: 2022,
    details: [
      {
        month: "Jan'23",
        numOfStudent: "200",
      },
      {
        month: "Feb'23",
        numOfStudent: "500",
      },
      {
        month: "Mar'23",
        numOfStudent: "400",
      },
      {
        month: "Apr'23",
        numOfStudent: "500",
      },
      {
        month: "May'23",
        numOfStudent: "800",
      },
      {
        month: "June'23",
        numOfStudent: "200",
      },
      {
        month: "July'23",
        numOfStudent: "600",
      },
      {
        month: "Aug'23",
        numOfStudent: "800",
      },
      {
        month: "Sep'23",
        numOfStudent: "400",
      },
      {
        month: "Oct'23",
        numOfStudent: "700",
      },
      {
        month: "Nov'23",
        numOfStudent: "700",
      },
      {
        month: "Des'23",
        numOfStudent: "300",
      },
    ],
  },
  {
    year: 2021,
    details: [
      {
        month: "Jan'23",
        numOfStudent: "700",
      },
      {
        month: "Feb'23",
        numOfStudent: "500",
      },
      {
        month: "Mar'23",
        numOfStudent: "800",
      },
      {
        month: "Apr'23",
        numOfStudent: "500",
      },
      {
        month: "May'23",
        numOfStudent: "600",
      },
      {
        month: "June'23",
        numOfStudent: "200",
      },
      {
        month: "July'23",
        numOfStudent: "400",
      },
      {
        month: "Aug'23",
        numOfStudent: "800",
      },
      {
        month: "Sep'23",
        numOfStudent: "400",
      },
      {
        month: "Oct'23",
        numOfStudent: "300",
      },
      {
        month: "Nov'23",
        numOfStudent: "700",
      },
      {
        month: "Des'23",
        numOfStudent: "200",
      },
    ],
  },
];

export const eventsLists = [
  {
    
    title: 'Palm Sunday',
    start: '2024-03-24T10:00:00',
    end: '2024-03-24T12:00:00',
    eventType: 'currentWeek',
    programName: 'Programming Workshop'
  },
  {
   
    title: 'Ester',
    start: '2024-03-31T12:00:00',
    end: '2024-03-31T12:00:00',
    eventType: 'upComing',
    programName: 'Programming Workshop'
  },
  {
   
    title: 'Good Friday',
    start: '2024-03-29T12:00:00',
    end: '2024-03-29T15:00:00',
    eventType: 'upComing',
    programName: 'Data Science Seminar'
  },
  {
    
    title: 'Birthday',
    start: '2024-03-15T18:00:00',
    end: '2024-03-15T20:00:00',
    eventType: 'finished',
    programName: 'Web Development Bootcamp'
  },
]
export const darkMode=[
  {
    mode:"false"
  }
]