import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/component/header/page";
import Footer from "@/component/footer/page";
import { Poppins } from "next/font/google";
import SideMenu from "@/component/sideMenu/page";
import { SideMenuProvider } from "@/component/sideMenuProvider/page";
import { Providers } from "@/redux/provider";
import { ThemeProvider } from "@/component/ThemeProvider/page";
import { ThemeSwitcher } from "@/component/ThemeSwitcher/page";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <Providers>
      <html lang="en">
        <body className={`${inter.className} ${poppins.className} bg-slate-50 dark:bg-[#000000]`} >
          {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher /> */}
            <SideMenuProvider>
              <Header />
              <div className="layout">
                <SideMenu />
                <div className="child">
                    {children}
                </div>
              </div>
            </SideMenuProvider>
            <Footer />
          {/* </ThemeProvider> */}
        </body>
      </html>
    </Providers>
  );
}
